---
title: "Staitistical Inference"
author: "Jin Kim"
date: "Thursday, October 01, 2015"
output: html_document
---

```{r, message=FALSE}
library(plyr)
library(dplyr)
library(ggplot2)
```


# Probability Distribution

```{r}
pk = 100000
p1 = rbinom(pk, 4, 0.2)
m1 = mean(p1); sd1 = sd(p1)
p2 = rnorm(pk, 2, 1)
m2 = mean(p2); sd2 = sd(p2)
p3 = runif(pk, 0, 3)
m3 = mean(p3); sd3 = sd(p3)

par(mfrow=c(1,3))
hist(p1, main="Population distribution: p1")
hist(p2, main="Population distribution: p2")
hist(p3, main="Population distribution: p3")
```

# Sampling Distribution

```{r}
k = 36
n = 1000
sdist = adply(1:n, 1, function(i){
	s1 = sample(p1, k)
	s2 = sample(p2, k)
	s3 = sample(p3, k)
	data.frame(m1 = mean(s1), m2 = mean(s2), m3 = mean(s3))
})

# Sampling Distribution
par(mfrow=c(1,3))
hist(sdist$m1, main="Sampling distribution: p1")
hist(sdist$m2, main="Sampling distribution: p2")
hist(sdist$m3, main="Sampling distribution: p3")
```

# Central Limit Throream
```{r}
par(mfrow=c(1,3))
plot(density(sdist$m1), main="Comparing sampling distribution: p1"); lines(density(rnorm(10000,m1,sd1/sqrt(k))), lty=2)
plot(density(sdist$m2), main="Comparing sampling distribution: p2"); lines(density(rnorm(10000,m2,sd2/sqrt(k))), lty=2)
plot(density(sdist$m3), main="Comparing sampling distribution: p3"); lines(density(rnorm(10000,m3,sd3/sqrt(k))), lty=2)
```

# Confidence Interval
```{r, fig.width=10}
#k = 144
k = 36
n = 100
conf.level = 0.95
z1 = qnorm((1-conf.level)/2)
z2 = qnorm(conf.level + (1-conf.level)/2)
t1 = qt((1-conf.level)/2, k-1)
t2 = qt(conf.level + (1-conf.level)/2, k-1)

ci.dist = adply(1:n, 1, function(i){
	s1 = sample(p1, k)
	stderr.a = sd(s1) / sqrt(length(s1))
	ci1 = mean(s1) + stderr.a * t1
	ci2 = mean(s1) + stderr.a * t2
	t = t.test(s1, mu=0.5)
	data.frame(i = i, m1 = mean(s1), ci1 = ci1, ci2 = ci2, 
			   ci.valid = ifelse(ci1 < m1 & m1 < ci2, 1, 0), 
			   ci.test = ifelse(ci1 > 0.5, 1, 0),
			   t.test = ifelse(t$p.value < 0.05, 1, 0),
			   p.value = t$p.value)
})

# Visualizing C.I.
summary(ci.dist)
ggplot(head(ci.dist, 100), aes(i, m1, ymin=ci1, ymax=ci2)) + geom_errorbar() + 
	geom_segment(aes(x=0, xend=100, y=mean(p1), yend=mean(p1))) +
	geom_segment(aes(x=0, xend=100, y=0.5, yend=0.5), colour = "red") +
	coord_cartesian(ylim=c(0,1.5))
```


