---
title: "From Excel to R"
author: "Jin Kim"
date: "Saturday, May 02, 2015"
output:
  html_document:
    keep_md: true
    toc: true
    toc_depth: 2
---
# Preparing Environemnt

```{r, eval=FALSE}
install.packages("stringr")
install.packages("ggplot2")
install.packages("dplyr")
```

```{r, message=FALSE}
library(stringr)
library(ggplot2)
library(dplyr)
setwd("c:/src/root/dbook")
```


# Defining Variables

```{r, eval=FALSE}
v1 = 1

v2 = "abc"

v3 = c(1,2,3)

df1 = data.frame(
	Name=c("Jerry","Tom","Smith"),
	Math=c(50,60,75))
```

# Reading & Writing Data

```{r}
write.table(mtcars, "clipboard")
write.table(mtcars, "mtcars_new.txt")
mcars = read.table("mtcars_new.txt", header=T)
```


# Learning about DataFrame

```{r}
head(mcars)
tail(mcars)
rownames(mcars)
colnames(mcars)
summary(mcars)
```

# Preparing the DataFrame

```{r}
mcars$model = rownames(mcars)
mcars$maker = word(mcars$model, 1)
rownames(mcars) = NULL
head(mcars)
```

# Summarizing the Data

```{r}
table(mcars$cyl)
table(mcars$gear, mcars$cyl)
```

# Working with DataFrame
## Working with DataFrame (basic)

```{r}
mcars$cyl == 4
mcars.small = mcars[mcars$cyl == 4, ] # filter rows
mcars.small.narrow = mcars.small[, c("model","maker", "mpg", "cyl")] # select columns by name
mcars.small.narrow = mcars.small[, c(12:13, 1:2)] # select columns by index
mcars.small.narrow
```

## Working with DataFrame (dplyr)

```{r}
mcars.small.narrow = # ????????? mcars.small.narrow?????? ????????? ????????????.
	mcars %>% # mcars???????????? ????????????.
	filter(cyl == 4) %>% # cyl?????? 4??? ???????????? ?????????.
	select(maker, model, mpg, cyl) # ????????? ??? ????????? ????????????.
mcars.small.narrow

makers = 
	mcars %>% 
	group_by(maker) %>% # ????????? ???????????? ???????????? ????????????.
	summarize( maker.mpg = mean(mpg), maker.count = n()) # ???????????? ?????? mpg??? ??? ?????? ??????
head(makers)

mcars.makers = merge(mcars, makers, by="maker")
head(mcars.makers)
```

# Plotting
## Basic Plotting
```{r ch2_plot_basic, fig.width=8}
hist(mcars$mpg)
plot(mcars[,1:5])
plot(mcars$wt, mcars$mpg)
par(mfrow=c(1,2))
plot(mpg ~ cyl, mcars)
plot(mpg ~ factor(cyl), mcars)
```

## Advanced Plotting
```{r ch2_plot_adv}
qplot(wt, mpg, data=mcars, color=wt)
qplot(wt, mpg, data=mcars, color=factor(cyl))
qplot(wt, mpg, data=mcars, geom = c("point", "smooth"))
```

