


# load libraries

```{r}
library(reshape2)   # needed for melt(), dcast()
library(stringr)    # needed for str_replace(), str_sub()
library(dplyr)      # needed for arrange(), select(), inner_join()
library(lubridate)  # needed for ymd(), weeks()
library(knitr)
library(ggplot2)
library(DT)
source("dbook/dbook.R")
```

# Problem 1: column headers are values instead of variable names

```{r, warning=FALSE}
# read pew.txt (tab-delimited file) into a data frame
pew.raw <- read.delim("dbook/ch3/pew.txt", check.names=FALSE, stringsAsFactors=FALSE)

# view data frame: variables are religion, income, count
datatable(pew.raw)

# melt pew.raw: second argument is columns that are already variables
pew.tidy <- melt(pew.raw, "religion")

# fix column names
names(pew.tidy) <- c("religion", "income", "count")

# Transform the range into number
pew.tidy$income.usd = sapply(pew.tidy$income, function(v){mean(sapply(str_extract_all(v, "\\d+"), as.integer))})
pew.tidy$income.krw = pew.tidy$income.usd * 1200
datatable(pew.tidy)

ggplot(pew.tidy, aes(income.krw, religion)) + geom_point(aes(size=count)) + 
	scale_size(range=c(1,10)) #+ xlab("??????(income.krw)") + ylab("??????(religion)")

```

## Aggregating the Income Distribution
```{r}
pew.agg = pew.tidy %>% filter(!is.na(income.krw)) %>% group_by(religion) %>% 
	summarize(total.count = sum(count), avg.income.krw = round(mean(income.krw*count) / sum(count)))

q1 = qplot(x=religion, y=total.count, data=pew.agg, geom="bar", width=0.5, stat="identity") + coord_flip()
q2 = qplot(x=religion, y=avg.income.krw, data=pew.agg, geom="bar", width=0.5, stat="identity") + coord_flip()
multiplot(q1, q2, cols=2)

```

## Group Religion by Type

```{r}

```


## Most Popular Religion in Each Group
```{r}
argmax <- function(arg, tgt){
	tgt[arg == max(arg)]
}
pew.agg = pew.tidy %>% 
	group_by(income) %>% summarize(major.religion = argmax(count, religion))
```


## Problem 4: multiple types in the same table

```{r}
# read billboard.csv (comma-separated file) into a data frame
billboard.raw <- read.csv("dbook/ch3/billboard.csv", stringsAsFactors = FALSE)

# view data frame: variables are artist, track, genre, time, date, week, rank
datatable(billboard.raw)

# remove an unnecessary column
billboard.raw$date.peaked <- NULL

# change encoding of artist column, then remove certain characters from track column
billboard.raw$artist.inverted <- iconv(billboard.raw$artist.inverted, from="MAC", to="UTF-8")
billboard.raw$track <- str_replace(billboard.raw$track, " \\(.*?\\)", "")

# change the names of every column (except for the first 6) to 1 through 76
names(billboard.raw)[-(1:6)] <- 1:76

# melt billboard.raw (except for the first 6 columns) and remove NA values
billboard.tidy <- melt(billboard.raw, 1:6, na.rm = TRUE)

# create a new variable "week" by converting "variable" from a factor to an integer
billboard.tidy$week <- as.integer(as.character(billboard.tidy$variable))

# remove the "variable" column, since it is no longer needed
billboard.tidy$variable <- NULL

# convert the date into a POSIXct object (so that we can do math on it)
billboard.tidy$date.entered <- ymd(billboard.tidy$date.entered)

# create an explicit date column as a function of "date.entered" and "week"
billboard.tidy$date <- billboard.tidy$date.entered + weeks(billboard.tidy$week - 1)

# remove the "date.entered" column, since it is no longer needed
billboard.tidy$date.entered <- NULL

# rename columns "artist.inverted" and "value"
names(billboard.tidy)[2] <- "artist"
names(billboard.tidy)[6] <- "rank"

# rearrange the data frame columns, then reorder the rows
billboard.tidy <- select(billboard.tidy, year, artist, track, time, genre,
                         week, date, rank)
billboard.tidy <- arrange(billboard.tidy, year, artist, track, week)

# create a new data frame for song information only, and remove the row names
billboard.song <- unique(select(billboard.tidy, artist, track, genre, time))
rownames(billboard.song) <- NULL

# add a new song_id column to billboard.song, then make it the first column
billboard.song$song_id <- 1:nrow(billboard.song)
billboard.song <- select(billboard.song, song_id, artist, track, genre, time)

# create a new data frame for rank information only
billboard.rank <- inner_join(billboard.tidy, billboard.song)
billboard.rank <- select(billboard.rank, song_id, week, date, rank)

datatable(billboard.rank)
```


