


# load libraries

```{r}
library(reshape2)   # needed for melt(), dcast()
library(stringr)    # needed for str_replace(), str_sub()
library(dplyr)      # needed for arrange(), select(), inner_join()
library(knitr)
library(ggplot2)
library(DT)
source("dbook/dbook.R")
```

# Problem 1: column headers are values instead of variable names

```{r, warning=FALSE}
# pew.txt??? ??????????????? ????????????.
pew.raw <- read.delim("dbook/ch3/pew.txt", check.names=FALSE, stringsAsFactors=FALSE)
head(pew.raw)

# religion ????????? ????????? ?????? ????????? ?????????(measure)?????? ????????????.
pew.tidy <- melt(pew.raw, "religion")

# ???????????? ?????? ????????? ????????????.
names(pew.tidy) <- c("religion", "income", "count")
head(pew.tidy)


# ?????? ????????? ???????????? ????????? ????????? ??????
range.to.number <- function(v){
	# ???????????? ???????????? ?????? ??????????????? ?????? ???????????? ?????? ????????????.
	range.values = str_extract_all(v, "\\d+")
	# ?????? ???????????? ??????????????? ????????? ??? ????????? ?????????.
	mean(sapply(range.values, as.integer))
}
range.to.number("$10k")
range.to.number("$10-20k")

# ?????? ?????? ????????? ????????????.
pew.tidy$income.usd = sapply(pew.tidy$income, range.to.number) * 1000
summary(pew.tidy$income.usd)

# ????????? ????????? ????????? ?????????.
pew.tidy = na.omit(pew.tidy)
head(pew.tidy)

qplot(income.usd, religion, data = pew.tidy, size=count)

```

## Aggregating the Income Distribution
```{r}
pew.agg = pew.tidy %>%     # ?????? ????????????
	group_by(religion) %>% # religion??? ???????????? ???????????????
	summarize(total.count = sum(count), # ?????? ????????? ??????
			  avg.income.usd = mean(income.usd*count) / sum(count)) # ?????? ????????? ????????????
head(pew.agg)

# ????????? ?????? ????????? ??? ??????
q1 = qplot(x=religion, y=total.count, data=pew.agg, geom="bar", # ????????? XY?????? ????????? ??? ????????? ????????????
		   width=0.5, stat="identity") + coord_flip()           # ????????? ?????? ????????? ????????? ????????????

# ????????? ?????? ?????? ??????
q2 = qplot(x=religion, y=avg.income.usd, data=pew.agg, geom="bar", 
		   width=0.5, stat="identity") + coord_flip()
multiplot(q1, q2, cols=2)

```

## Most Popular Religion in Each Group
```{r}
argmax <- function(arg, tgt){
	tgt[arg == max(arg)]
}
pew.agg = pew.tidy %>% 
	group_by(income) %>% summarize(major.religion = argmax(count, religion))
```



